# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    status.mysql:
        class: AppBundle\Service\Status\Mysql
        arguments: ['@database_connection']
    status.redis:
        class: AppBundle\Service\Status\Redis
        arguments: ['@snc_redis.default']
    status.health:
        class: AppBundle\Service\Check
        arguments: [{'MYSQL' : '@status.mysql', 'REDIS' : '@status.redis'}]

